#!/bin/bash
set -e

# 定义安装目录
INSTALL_DIR="/app"
CONFIG_FILE="$INSTALL_DIR/config.yaml"

# ----------------------------------------------------------------
# HF_SAVE Keepalive Logic
# ----------------------------------------------------------------
if [ -n "$HF_SAVE" ]; then
    # Format: username/space_name -> https://username-space_name.hf.space/
    # Replace the first slash with a hyphen
    HF_URL="https://$(echo "$HF_SAVE" | sed 's/\//-/').hf.space/"
    echo "Starting HF_SAVE keepalive for: $HF_URL"
    
    # Run loop in background
    (
        while true; do
            # Run only if curl or wget exists
            if command -v curl > /dev/null; then
                curl -s "$HF_URL" > /dev/null || echo "[HF_SAVE] Keepalive ping failed"
            else
                wget -qO- "$HF_URL" > /dev/null || echo "[HF_SAVE] Keepalive ping failed"
            fi
            sleep 300 # 5 minutes
        done
    ) &
fi

# ----------------------------------------------------------------
# Dynamic Configuration Generation Logic
# ----------------------------------------------------------------

echo "Generating config.yaml from environment variables (Overwriting existing)..."

# --- Basic Config ---
PORT=${CLIPROXY_PORT:-8317}
HOST=${CLIPROXY_HOST:-"0.0.0.0"}

# --- API Keys ---
if [ -z "$CLIPROXY_API_KEYS" ]; then
    echo "WARNING: No API Keys provided in CLIPROXY_API_KEYS. Generating a random one."
    RANDOM_KEY="sk-$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 45 | head -n 1)"
    KEYS_YAML="  - \"$RANDOM_KEY\""
    echo "Generated Random Key: $RANDOM_KEY"
else
    KEYS_YAML=$(echo "$CLIPROXY_API_KEYS" | tr ',' '\n' | sed 's/^/  - "/;s/$/"/')
fi

# --- Management Interface ---
MANAGEMENT_ENABLED=${CLIPROXY_MANAGEMENT_ENABLED:-true}
MANAGEMENT_KEY=${CLIPROXY_MANAGEMENT_KEY:-"admin"}
ALLOW_REMOTE=${CLIPROXY_MANAGEMENT_ALLOW_REMOTE:-true}

# --- Advanced Options (Default values from config.yml.example) ---
DEBUG=${CLIPROXY_DEBUG:-false}
COMMERCIAL_MODE=${CLIPROXY_COMMERCIAL_MODE:-false}
LOGGING_TO_FILE=${CLIPROXY_LOGGING_TO_FILE:-false}
PROXY_URL=${CLIPROXY_PROXY_URL:-""}
FORCE_MODEL_PREFIX=${CLIPROXY_FORCE_MODEL_PREFIX:-false}
REQUEST_RETRY=${CLIPROXY_REQUEST_RETRY:-3}
MAX_RETRY_INTERVAL=${CLIPROXY_MAX_RETRY_INTERVAL:-30}
ROUTING_STRATEGY=${CLIPROXY_ROUTING_STRATEGY:-"round-robin"}
WS_AUTH=${CLIPROXY_WS_AUTH:-false}

# --- Generate config.yaml ---
cat > "$CONFIG_FILE" <<EOF
# Generated by Docker Entrypoint
# Server host/interface to bind to. Default is empty ("") to bind all interfaces (IPv4 + IPv6).
# Use "127.0.0.1" or "localhost" to restrict access to local machine only.
host: "$HOST"

# Server port
port: $PORT

# TLS settings for HTTPS. When enabled, the server listens with the provided certificate and key.
tls:
  enable: false
  cert: ""
  key: ""

# Management API settings
remote-management:
  # Whether to allow remote (non-localhost) management access.
  # When false, only localhost can access management endpoints (a key is still required).
  allow-remote: $ALLOW_REMOTE

  # Management key. If a plaintext value is provided here, it will be hashed on startup.
  # All management requests (even from localhost) require this key.
  # Leave empty to disable the Management API entirely (404 for all /v0/management routes).
  secret-key: "$MANAGEMENT_KEY"

  # Disable the bundled management control panel asset download and HTTP route when true.
  disable-control-panel: false

  # GitHub repository for the management control panel. Accepts a repository URL or releases API URL.
  panel-github-repository: "https://github.com/router-for-me/Cli-Proxy-API-Management-Center"

# Authentication directory (supports ~ for home directory)
auth-dir: "/app/.cli-proxy-api"

# API keys for authentication
api-keys:
$KEYS_YAML

# Enable debug logging
debug: $DEBUG

# When true, disable high-overhead HTTP middleware features to reduce per-request memory usage under high concurrency.
commercial-mode: $COMMERCIAL_MODE

# When true, write application logs to rotating files instead of stdout
logging-to-file: $LOGGING_TO_FILE

# Maximum total size (MB) of log files under the logs directory. When exceeded, the oldest log
# files are deleted until within the limit. Set to 0 to disable.
logs-max-total-size-mb: 0

# When false, disable in-memory usage statistics aggregation
usage-statistics-enabled: false

# Proxy URL. Supports socks5/http/https protocols. Example: socks5://user:pass@192.168.1.1:1080/
proxy-url: "$PROXY_URL"

# When true, unprefixed model requests only use credentials without a prefix (except when prefix == model name).
force-model-prefix: $FORCE_MODEL_PREFIX

# Number of times to retry a request. Retries will occur if the HTTP response code is 403, 408, 500, 502, 503, or 504.
request-retry: $REQUEST_RETRY

# Maximum wait time in seconds for a cooled-down credential before triggering a retry.
max-retry-interval: $MAX_RETRY_INTERVAL

# Quota exceeded behavior
quota-exceeded:
  switch-project: true # Whether to automatically switch to another project when a quota is exceeded
  switch-preview-model: true # Whether to automatically switch to a preview model when a quota is exceeded

# Routing strategy for selecting credentials when multiple match.
routing:
  strategy: "$ROUTING_STRATEGY" # round-robin (default), fill-first

# When true, enable authentication for the WebSocket API (/v1/ws).
ws-auth: $WS_AUTH

# When > 0, emit blank lines every N seconds for non-streaming responses to prevent idle timeouts.
nonstream-keepalive-interval: 0

# Streaming behavior (SSE keep-alives + safe bootstrap retries).
# streaming:
#   keepalive-seconds: 15   # Default: 0 (disabled). <= 0 disables keep-alives.
#   bootstrap-retries: 1    # Default: 0 (disabled). Retries before first byte is sent.

# When true, enable official Codex instructions injection for Codex API requests.
# When false (default), CodexInstructionsForModel returns immediately without modification.
codex-instructions-enabled: false

# Note: Complex Provider configurations (Gemini/Claude/Codex API Key lists) 
# are recommended to be appended via the CLIPROXY_ADDITIONAL_CONFIG environment variable.
EOF

# If there is an additional configuration block (for injecting complex provider configs), append it to the end of the file
if [ -n "$CLIPROXY_ADDITIONAL_CONFIG" ]; then
    echo -e "\n$CLIPROXY_ADDITIONAL_CONFIG" >> "$CONFIG_FILE"
fi

echo "✅ config.yaml generated successfully."

# ----------------------------------------------------------------
# Start Application
# ----------------------------------------------------------------
echo "🚀 Starting CLIProxyAPI..."
exec "$INSTALL_DIR/cli-proxy-api"
